# Generated by Django 5.2.3 on 2025-08-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(choices=[('ACC', 'Acción'), ('TER', 'Terror'), ('AVN', 'Aventura'), ('CAR', 'Carreras'), ('DIV', 'Diversión'), ('MAB', 'Mundo Abierto'), ('SHO', 'Shooter'), ('MUL', 'Multijugador'), ('PEL', 'Pelea'), ('OTR', 'Otros')], default='OTR', max_length=3),
        ),
    ]
